version = 10

[[shader_sessions]]
root_directory = "Shaders"
session_name = "game"
debug_symbols = false
optimization = "default"

[[shader_sessions.programs]]
name = "crt"
path = "crt.slang"
entry_points = ["vs_main", "fs_main"]
